### ISSUE TITLE
Publish somewhere

### ISSUE THREAD

**Issue by strugee** [roundcube/roundcubemail-helpdocs#2]
Currently, there seems to be no place on the web where these docs are available in a built form. http://docs.roundcube.net/doc/help/1.1/en_US/?_framed=1 is broken, which means that Roundcube's `help` plugin with the defaults is basically useless - and because there isn't another location for these docs, there isn't anywhere decent to set [`$config['help_source']`](https://github.com/roundcube/roundcubemail/blob/eaf08e58e80eccd3cd1d5707ac10fe019946d596/plugins/help/config.inc.php.dist#L8) to.

**Comment by pabzm** [comment]
Thank you for caring!

Unfortunately these docs aren't properly maintained. E.g. they still refer to the "larry" skin, which isn't default anymore since 5 years. So I'm afraid in the current state they wouldn't help much, even if they'd be re-published.

Would you maybe be interested in fixing them up as a contribution?

**Comment by strugee** [comment]
It certainly occurred to me :D though I am pretty busy with [other](https://seagl.org) [things](https://tech.lgbt/@strugee/113026547936559459). I noticed the last commit date last night so I'm not surprised. 

Do you have a ballpark estimate of how long it would take to get these up to date?

**Comment by pabzm** [comment]
Best I can estimate is "a single digit of hours", sorry. (Because it would include making screenshots and edit them to highlight buttons etc.) Most texts are still roughly correct, I think.

Contributing a part (e.g. the screenshots) would also be very appreciated! But I understand if you'd decline, being busy yourself!

**Comment by pabzm** [comment]
https://docs.roundcube.net/1.1/en/ is now back to life.

I'll build a simple index page and a disclaimer, that the content is outdated. Changing the content (and maybe refreshing the styling 😬)  is another task.

**Comment by strugee** [comment]
Awesome. Thanks for caring :-)
